#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RaysHotDogs.Resource", IsApplication=true)]

namespace RaysHotDogs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int FavoritesIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int MeatLoversIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int RayLogo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int smallicon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int VeggieLoversIcon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060012
			public const int aboutButton = 2131099666;
			
			// aapt resource value: 0x7f06000a
			public const int amountEditText = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int callTextView = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int cancelButton = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int cartButton = 2131099663;
			
			// aapt resource value: 0x7f060007
			public const int descriptionTextView = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int fragmentContainer = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int hotDogImageView = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int hotDogListView = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int hotDogNameTextView = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int logoImageView = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int mainScrollView = 2131099651;
			
			// aapt resource value: 0x7f060011
			public const int mapButton = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int myButton = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int orderButton = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int phoneNumberTextView = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int priceTextView = 2131099656;
			
			// aapt resource value: 0x7f060014
			public const int rayPictureImageView = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int shortDescriptionTextView = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int takePictureButton = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int textView1 = 2131099667;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AboutView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FavoriteHotDogFragment = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int HotDogDetailView = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int HotDogMenuView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int HotDogRowView = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Main = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int MainMenu = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int MeatLoversFragment = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int TakePictureView = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int VeggieLoversFragment = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
